from __future__ import annotations

import json
import os
from dataclasses import dataclass

import google.generativeai as genai
from dotenv import load_dotenv

from ..models.events import DomainError


@dataclass
class GeminiDecisionOutput:
    recommendation: str
    decision_basis_summary: str
    confidence_score: float | None = None


@dataclass
class GeminiCreditOutput:
    risk_tier: str
    recommended_limit_usd: float
    confidence_score: float
    analysis_duration_ms: int = 0


@dataclass
class GeminiFraudOutput:
    fraud_score: float
    anomaly_flags: list[str]


@dataclass
class GeminiComplianceOutput:
    remediation_required: bool
    failure_reason: str


class GeminiDecisionAgent:
    """
    Thin Gemini-backed decision helper used by MCP tooling.
    It does not append events directly; command handlers remain the source of writes.
    """

    def __init__(self, model: str = "gemini-1.5-flash") -> None:
        # Load .env from project root if present (safe no-op otherwise).
        load_dotenv()
        api_key = os.environ.get("GEMINI_API_KEY")
        if not api_key:
            raise DomainError(
                "GEMINI_API_KEY is required for Gemini agent operations",
                code="MISSING_GEMINI_API_KEY",
            )
        genai.configure(api_key=api_key)
        self._model = genai.GenerativeModel(model)

    def generate_decision(self, payload: dict) -> GeminiDecisionOutput:
        prompt = _build_prompt(payload)
        resp = self._model.generate_content(prompt)
        text = (resp.text or "").strip()
        parsed = _parse_json_response(text)

        recommendation = str(parsed.get("recommendation", "REFER")).upper()
        if recommendation not in {"APPROVE", "DECLINE", "REFER"}:
            recommendation = "REFER"

        summary = str(parsed.get("decision_basis_summary", "")).strip()
        if not summary:
            summary = "Generated by Gemini agent based on provided analysis context."

        conf = parsed.get("confidence_score")
        confidence_score = None
        if isinstance(conf, (int, float)):
            confidence_score = max(0.0, min(1.0, float(conf)))

        return GeminiDecisionOutput(
            recommendation=recommendation,
            decision_basis_summary=summary,
            confidence_score=confidence_score,
        )

    def analyze_credit(self, payload: dict) -> GeminiCreditOutput:
        prompt = (
            "Return strict JSON with keys: risk_tier, recommended_limit_usd, confidence_score, analysis_duration_ms.\n"
            "risk_tier must be LOW, MEDIUM, or HIGH. confidence_score in [0,1].\n"
            f"Input:\n{json.dumps(payload, default=str)}"
        )
        parsed = _parse_json_response((self._model.generate_content(prompt).text or "").strip())
        risk_tier = str(parsed.get("risk_tier", "MEDIUM")).upper()
        if risk_tier not in {"LOW", "MEDIUM", "HIGH"}:
            risk_tier = "MEDIUM"
        limit_val = parsed.get("recommended_limit_usd", payload.get("requested_amount_usd", 0) or 0)
        try:
            limit = max(0.0, float(limit_val))
        except Exception:
            limit = 0.0
        conf = parsed.get("confidence_score", 0.7)
        try:
            confidence = max(0.0, min(1.0, float(conf)))
        except Exception:
            confidence = 0.7
        dur = parsed.get("analysis_duration_ms", 0)
        try:
            duration = max(0, int(dur))
        except Exception:
            duration = 0
        return GeminiCreditOutput(risk_tier=risk_tier, recommended_limit_usd=limit, confidence_score=confidence, analysis_duration_ms=duration)

    def analyze_fraud(self, payload: dict) -> GeminiFraudOutput:
        prompt = (
            "Return strict JSON with keys: fraud_score, anomaly_flags.\n"
            "fraud_score must be between 0 and 1. anomaly_flags must be a list of short strings.\n"
            f"Input:\n{json.dumps(payload, default=str)}"
        )
        parsed = _parse_json_response((self._model.generate_content(prompt).text or "").strip())
        score = parsed.get("fraud_score", 0.1)
        try:
            fraud_score = max(0.0, min(1.0, float(score)))
        except Exception:
            fraud_score = 0.1
        flags = parsed.get("anomaly_flags", [])
        if not isinstance(flags, list):
            flags = []
        flags = [str(x) for x in flags[:10]]
        return GeminiFraudOutput(fraud_score=fraud_score, anomaly_flags=flags)

    def summarize_compliance_failure(self, payload: dict) -> GeminiComplianceOutput:
        prompt = (
            "Return strict JSON with keys: remediation_required (bool), failure_reason (string).\n"
            "Use concise audit-ready wording.\n"
            f"Input:\n{json.dumps(payload, default=str)}"
        )
        parsed = _parse_json_response((self._model.generate_content(prompt).text or "").strip())
        remediation_required = bool(parsed.get("remediation_required", False))
        failure_reason = str(parsed.get("failure_reason", "")).strip() or "Compliance condition failed."
        return GeminiComplianceOutput(remediation_required=remediation_required, failure_reason=failure_reason)


def _build_prompt(payload: dict) -> str:
    return (
        "You are a lending decision assistant. "
        "Return strict JSON with keys: recommendation, decision_basis_summary, confidence_score.\n"
        "Rules:\n"
        "- recommendation must be one of APPROVE, DECLINE, REFER\n"
        "- if confidence_score < 0.60, set recommendation=REFER\n"
        "- decision_basis_summary must be concise (1-3 sentences)\n\n"
        f"Input:\n{json.dumps(payload, default=str)}"
    )


def _parse_json_response(text: str) -> dict:
    # Handles plain JSON or fenced markdown JSON.
    cleaned = text.strip()
    if cleaned.startswith("```"):
        cleaned = cleaned.strip("`")
        if cleaned.startswith("json"):
            cleaned = cleaned[4:].strip()
    try:
        value = json.loads(cleaned)
        if isinstance(value, dict):
            return value
    except Exception:
        pass
    return {}
